name: Mirror all repos to Codeberg123

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # daily at 03:00

env:
  SKIP_REPOS: github-mirror-controller
  CODEBERG_OWNER: kaywoz

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y git jq gh

      - name: Setup SSH for Codeberg
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEBERG_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: List all GitHub repositories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo list ${{ github.repository_owner }} \
            --limit 1000 \
            --json name,httpsUrl \
            --jq '.[] | "\(.name) \(.url)"' > repos.txt

      - name: Mirror repositories to Codeberg
        run: |
          while read name repoUrl; do
            if [[ "$SKIP_REPOS" == *"$name"* ]]; then
              echo "Skipping $name"
              continue
            fi

            echo "=== Mirroring $name ==="

            rm -rf "$name.git"
            git clone --mirror "$repoUrl" "$name.git"

            cd "$name.git"
            git push --mirror "git@codeberg.org:${CODEBERG_OWNER}/$name.git" || true
            cd ..
          done < repos.txt
